[tool.black]
line-length = 120
target-version = ['py310']

[tool.pyright]
include = ["ottbot_v5", "noxfile.py"]
pythonVersion="3.10"
reportMissingImports=false
reportInvalidTypeVarUse=false
reportMissingModuleSource=false
pythonPlatform="Linux"

[tool.mypy]
mypy_path="./typings/"

[tool.isort]
profile="black"
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
skip_glob = "**/__init__.pyi"
