import typing as t

class Record:
    def __len__(self) -> int: ...
    def __getitem__(self, item: t.Any) -> t.Any: ...
    def __contains__(self) -> bool: ...
    def __iter__(self) -> "Record": ...
    def __next__(self) -> t.Any: ...
    def get(self, name: t.Any, default: t.Any | None = ...) -> t.Any | None: ...
    def keys(self) -> list[t.Any]: ...
    def values(self) -> list[t.Any]: ...
    def items(self) -> t.Mapping[t.Any, t.Any]: ...
